device_list_name: "SD95 3MP"
uid: '952700Y003WBER6M'

ipc:
  light:
    text:
      - ''

    items:
      light:
        text:
          - '状态灯'
          - '红外灯'

        status_lights: '状态灯(有则保留无则删除)'

        infrared_light:
          options:
            - '亮度'

