device_list_name: "523-RLC-510A"
uid: '952700Y000ZNB2A1'

ipc:
  light:
    text:
      - ''

    items:
      light:
        text:
          - '红外灯'

        infrared_light:
          options:
            - ''

