device_list_name: FE-12
uid: 952700Y007GO1R75

ipc:
  light:
    text:
      - ''

    items:
      light:
        text:
          - '红外灯'

        infrared_light:
          options:
            - ''

