device_list_name: "RLC-1240A"
uid: '952700Y101041T6S'

ipc:
  camera_record:
    items:
      alarm_recording_plan:
        alarm_type:
          options:
            - '画面变动'
            - '人'
            - '车'
            - '动物'

      record_delay_duration:
        options:
          - '15秒'
          - '30秒'
          - '1分钟'

      pre_record: '预录像（有则保留无则删除）'

      timed_recording_plan:
        alarm_type:
          options:
            - ''


