device_list_name: "sd11"
uid: '952700Y100AALKZY'

ipc:
  light:
    name: '灯'
    desc: '设置>灯'
    type: 'navigation'
    text:
      - ''

    items:
      light:
        name: '灯'
        desc: '设置>灯主页'
        type: 'page'
        text:
          - '状态灯'
          - '红外灯'
          - '白光灯'

        status_lights: '状态灯/指示灯'

        infrared_light:
          options:
            - ''

        floodlight:
          light_off_mode:
            name: '关闭'
            desc: '设置>灯>白光灯>关闭'
            type: 'menu'
            text:
              - ''

          night_smart_mode:
            name: '夜间智能模式'
            desc: '设置>灯>照明灯>夜间智能模式'
            type: 'menu'
            text:
              - ''

          preview_opens_auto:
            name: '预览自动开启'
            desc: '设置>灯>照明灯>预览自动开启'
            type: 'switch'