device_list_name: "Reolink Duo 2V PoE"
uid: '95270008YNQN915C'

ipc:
  display:
    name: '显示'
    desc: '设置>显示'
    type: 'navigation'

    items:
      display:
        name: '显示'
        desc: '设置>显示'
        type: 'navigation'
        text:
          - '码流'
          - '移动标记'
          - '画面为清晰时，智能检测到移动事物将进行标记。'
          - '设备名称'
          - '日期'
          - '水印'
          - '图像设置'
          - '白天和黑夜'
          - '遮盖区域'
          - '拼接设置'
        options:
          - '码流'
          - '移动标记'
          - '设备名称'
          - '日期'
          - '水印'
          - '图像设置'
          - '白天和黑夜'
          - '遮盖区域'
          - '拼接设置'

        motion_mark: '移动标记(无需配置，有则保留无则删除)'
        device_name: '设备名称(无需配置，有则保留无则删除)'
        date: '日期(无需配置，有则保留无则删除)'
        watermark: '水印(无需配置，有则保留无则删除)'
        splice_region: '拼接区域(无需配置，有则保留无则删除)'


        private_mark:
          name: '遮盖区域'
          desc: '设置>显示>遮盖区域'
          type: 'navigation'
          camera_type: 'DM'
          mask_num: 4

        stream:
          name: '码流'
          desc: '设置>显示>码流（只需确认编码格式/I帧间隔/帧率控制/码率控制是否存在）'
          type: 'navigation'
          text:
            - '码率模式'
            - 'I 帧间隔'
          options:
            - '帧率控制'
            - '码率模式'

          clear:
            name: '清晰'
            desc: '设置>显示>码流>码流>清晰(此处的text也等于options)'
            type: '（只需确认编码格式/I帧间隔是否存在）'
            text:
              - 'I 帧间隔'

            resolution:
              desc: 设置>显示>码流>码流>清晰>分辨率
              name: 分辨率
              options:
                - '5120*1552'
                - '4096*1248'

            frame_rate:
              desc: 设置>显示>码流>码流>清晰>帧率(FPS)
              name: 帧率(FPS)
              options:
                - '20(默认)'
                - '18'
                - '16'
                - '15'
                - '12'
                - '10'
                - '8'
                - '6'

            max_bit_rate:
              desc: 设置>显示>码流>码流>清晰>最大码率(Kbps)
              name: 最大码率(Kbps)
              options:
                - '3072'
                - '4096'
                - '5120'
                - '6144'
                - '7168(默认)'
                - '8192'
                - '9216'

            i_frame_interval:
              desc: 设置>显示>码流>码流>清晰>I 帧间隔
              name: I 帧间隔
              options:
                - 1x
                - 2x


          fluent:
            name: '流畅'
            desc: '设置>显示>码流>码流>流畅'
            type: '（只需确认编码格式/I帧间隔是否存在）'
            text:
              - 'I 帧间隔'

            resolution:
              options:
                - '1920*576'

            frame_rate:
              options:
                - '20(默认)'
                - '15'
                - '10'
                - '7'
                - '4'

            i_frame_interval:
              options:
                - 1x
                - 2x
                - 3x
                - 4x

            max_bit_rate:
              options:
                - '256'
                - '512'
                - '1024(默认)'
                - '1536'
                - '2048'


          frame_rate_mode:
            name: '帧率控制(A代表自动，B代表恒定，C代表逐步)'
            desc: '设置>显示>码流>码流>帧率控制'
            support_mode: 'AB'

          rate_mode:
            name: '码率控制'

        image_setting:
          name: '图像设置(只需要确认亮度同步/hdr/夜视通透模式/抗闪烁)'

          brightness: '亮度'
          contrast: '对比度'
          saturation: '饱和度'
          sharpness: '锐度'
          brightness_sync: false
          hdr: false
          night_transparent_vision: false
          anti_flicker: true
          night_vision_zoom_enhance: false

        day_and_night:
          name: '白天和黑夜'
          desc: '白天和黑夜'
          type: 'popup'
          text:
            - '白天和黑夜'
            - '模式切换'
            - '高光/阴影调节'
            - '黑白'
            - '白天彩色'
            - '夜视彩色'
          options:
            - '模式切换'
            - '黑白'
            - '白天彩色'
            - '夜视彩色'

          mode_switching:
            name: '模式切换'
            desc: '白天和黑夜>模式切换'
            type: 'popup'
            text:
              - '模式切换'
              - '黑白'
              - '彩色'
              - '自动'
              - '光线较亮时自动显示彩色，较暗时自动显示黑白。'
              - '日夜切换阈值'
              - '白天和黑夜自动模式下，黑白彩色切换的环境亮度阈值：'
              - '恢复默认值'
              - '0'
              - '100'
            options:
              - '黑白'
              - '彩色'
              - '自动'
              - '日夜切换阈值'

          day_color:
            name: '白天彩色'
            desc: '白天和黑夜>白天彩色'
            type: 'popup'
            text:
              - '白天彩色'
              - '自动'
              - '手动'
              - '亮度'
              - '恢复默认值'
              - '暗部'
              - '0'
              - '255'
            options:
              - '自动'
              - '手动'
              - '亮度'
              - '暗部'

          black_and_white:
            name: '黑白'
            desc: '白天和黑夜>黑白'
            type: 'popup'
            text:
              - '黑白'
              - '自动'
              - '手动'
              - '亮度'
              - '恢复默认值'
              - '暗部'
              - '0'
              - '255'
            options:
              - '自动'
              - '手动'
              - '亮度'
              - '暗部'

          night_vision_color:
            name: '夜视彩色'
            desc: '白天和黑夜>夜视彩色'
            type: 'popup'
            text:
              - '夜视彩色'
              - '自动'
              - '手动'
              - '亮度'
              - '恢复默认值'
              - '暗部'
              - '0'
              - '255'
            options:
              - '自动'
              - '手动'
              - '亮度'
              - '暗部'



