device_list_name: "Reolink Altas PT Ultra"
uid: '952700Y100BF19GB'

ipc:
  light:
    text:
      - ''

    items:
      light:
        text:
          - '状态灯'
          - '白光灯'

        status_lights: '状态灯/指示灯'

        floodlight:
          light_off_mode:
            name: '关闭'
            desc: '设置>灯>白光灯>关闭'
            type: 'menu'
            text:
              - ''

          auto_mode:
            name: '自动模式'
            desc: '设置>灯>照明灯>自动模式'
            type: 'menu'
            text:
              - ''