device_list_name: "Reolink Lumus"
uid: '952700Y006BDF1TT'

ipc:
  light:
    text:
      - ''

    items:
      light:
        text:
          - '状态灯'
          - '红外灯'
          - '白光灯'

        status_lights: '状态灯'

        infrared_light:
          options:
            - ''

        floodlight:
          light_off_mode:
            name: '关闭'
            desc: '设置>灯>白光灯>关闭'
            type: 'menu'
            text:
              - ''

          night_smart_mode:
            detect_type:
              option_text:
                - ''
