device_list_name: "Reolink Altas PT Ultra"
uid: '952700Y100BF19GB'

ipc:
  push:
    items:
      visitor_phone_remind: '访客电话提醒'

      device_notify_ringtone:
        alarm_ring: '报警铃声'

      schedule:
        alarm_type:
          options:
            - '画面变动'
            - '人'
            - '车'
            - '动物'

      push_interval:
        options:
          - '20'
          - '30'
          - '60'
          - '120'

      delay_notifications:
        delay_time:
          options:
            - '20'
            - '30'
            - '60'
            - '120'
