device_list_name: "Reolink Go Ranger PT"
uid: '952700Y004WOIYNY'

ipc:
  light:
    name: '灯'
    desc: '设置>灯'
    type: 'navigation'
    text:
      - ''

    items:
      light:
        text:
          - '红外灯'

        infrared_light: '红外灯'