device_list_name: "RLC-542WA-5"
uid: '952700Y100U51Q5X'

ipc:
  light:
    text:
      - ''

    items:
      light:
        text:
          - '红外灯'

        infrared_light:
          options:
            - ''

