device_list_name: "Reolink Duo Floodlight WiFi v2"
uid: '952700Y007J01KT1'

ipc:
  light:
    text:
      - ''

    items:
      light:
        text:
          - '红外灯'
          - '照明灯'

        infrared_light:
          options:
            - ''

        floodlight:
          light_off_mode: '关闭'
          timer_mode: '定时模式'
          night_smart_mode:
            detect_type:
              option_text:
                  - '人'
                  - '车'
                  - '动物'
          night_vision_steady_light: '夜视常亮'
