device_list_name: yulong-test-sd7
uid: 952700Y006ZP1IJ5

ipc:
  camera_record:
    items:
      alarm_recording_plan:
        alarm_type:
          options:
          - 画面变动
          - 人
          - 车
          - 动物
          - 其他

      pre_record: 预录像

      record_delay_duration:
        options:
          - 15秒
          - 30秒
          - 1分钟

      timed_recording_plan:
        alarm_type:
          options:
            - ''




