device_list_name: yulong-test-sd7
uid: 952700Y006ZP1IJ5

ipc:
  light:
    text:
      - ''

    items:
      light:
        text:
          - 白光灯
          - 红外灯

        floodlight:
          light_off_mode: '关闭'
          night_smart_mode:
            detect_type:
              option_text:
              - 人
              - 车
              - 动物
          timer_mode: 定时模式
          brightness: '亮度(有则保留无则删除)'

        infrared_light:
          options:
            - ''



