device_list_name: yulong-test-sd7

ipc:
  light:
    desc: 设置>灯
    items:
      light:
        desc: 设置>灯主页
        floodlight:
          desc: 设置>灯>照明灯
          light_off_mode:
            desc: 设置>灯>照明灯>关闭
            name: 关闭
            text:
            - ''
            type: menu
          name: 照明灯
          night_smart_mode:
            desc: 设置>灯>照明灯>夜间智能模式
            detect_type:
              desc: 设置>灯>照明灯>夜间智能模式>侦测
              option_text:
              - 人
              - 车
              - 动物
              text:
              - 报警类型
              - 保存
              - 全选
              - 画面变动
              - 人
              - 车
              - 动物
              type: navigation
            name: 夜间智能模式
            text:
            - ''
            type: menu
          options:
          - 关闭
          - 夜间智能模式
          - 定时模式
          text:
          - 关闭
          - 白光灯将保持关闭
          - 夜间智能模式
          - 当相机在夜间检测到事件时自动打开。
          - 定时模式
          - 在预定的时间段内保持开启。
          timer_mode:
            desc: 设置>灯>照明灯>定时模式
            name: 定时模式
            text:
            - ''
            type: menu
          type: navigation
        infrared_light:
          desc: 设置>灯>红外灯
          name: 红外灯
          options:
          - 关闭
          - 自动
          text:
          - 红外灯
          - 红外灯补光时，能让你在夜晚或光线较暗时拍出更清晰的影像。
          - 关
          - 开
          - 关闭
          - 关闭红外灯后，夜视环境下效果会较差。
          - 自动
          - 光线较亮时自动开启，光线较暗时自动关闭。
          type: navigation
        name: 灯
        text:
        - 照明灯
        - 红外灯
        type: page
    name: 灯
    text:
    - ''
    type: navigation
uid: 952700Y006ZP1IJ5
