device_list_name: "yulong-test-sd7"
uid: '952700Y006ZP1IJ5'

ipc:
  push:


    items:
      supported_test: '是否支持测试按钮，支持就保留该键，否则删除'

      schedule:
        alarm_type:
          options:
            - '画面变动'
            - '人'
            - '车'
            - '动物'

      push_interval:
        options:
          - '20秒'
          - '30秒'
          - '60秒'
          - '120秒'

