device_list_name: yulong-test-sd7
uid: 952700Y006ZP1IJ5

ipc:
  Wi_Fi:
    text:
      - ''

    items:
      wifi:
        wifi_band_preference:
          options:
            - '仅 2.4G'
            - '仅 5G'
            - '自动'
        wifi_speed_test: 'WiFi测速'
        add_other_network: '添加其他网络'
