device_list_name: "SD93 4G"
uid: '952700Y004FC1YY2'

ipc:
  light:
    text:
      - ''

    items:
      light:
        text:
          - '红外灯'

        infrared_light:
          options:
            - ''


