device_list_name: E1 Outdoor CX-2
uid: 952700Y100YCX9H0

ipc:
  light:
    text:
      - ''

    items:
      light:
        text:
          - '状态灯'
          - '白光灯'


        status_lights: '状态灯(有则保留无则删除)'

        floodlight:
          light_off_mode: '关闭(有则保留无则删除)'
          brightness: '亮度(有则保留无则删除)'
          timer_mode: '定时模式(有则保留无则删除)'
          auto_mode: '自动模式(有则保留无则删除)'
          smart_mode:
            detect_type:
              option_text:
                - '人'
                - '车'
                - '动物'

