device_list_name: "Reolink Altas PT Ultra"
uid: '95270000Y5RRXWYC'

ipc:
  light:
    text:
      - ''

    items:
      light:
        text:
          - '状态灯'
          - '白光灯'

        status_lights: '状态灯(有则保留无则删除)'


        floodlight:
          light_off_mode: '关闭(有则保留无则删除)'
          brightness: '亮度(有则保留无则删除)'
          auto_mode: '自动模式(有则保留无则删除)'

