device_list_name: FE-P
uid: 952700Y100YU3HEV

ipc:
  display:
    items:
      display:
        day_and_night:
          options:
            - 模式切换
            - 黑白
            - 白天彩色
          text:
            - 白天和黑夜
            - 模式切换
            - 高光/阴影调节
            - 黑白
            - 白天彩色

          black_and_white:
            desc: 白天和黑夜>黑白
            name: 黑白
            options:
              - 自动
              - 手动
              - 亮度
              - 暗部
            text:
              - 黑白
              - 自动
              - 手动
              - 亮度
              - 恢复默认值
              - 暗部
              - '0'
              - '255'
            
          day_color:
            desc: 白天和黑夜>白天彩色
            name: 白天彩色
            options:
            - 自动
            - 手动
            - 亮度
            - 暗部
            text:
            - 白天彩色
            - 自动
            - 手动
            - 亮度
            - 恢复默认值
            - 暗部
            - '0'
            - '255'
            

          mode_switching:
            options:
              - 黑白
              - 彩色
              - 自动
              - 日夜切换阈值
            text:
              - 模式切换
              - 黑白
              - 彩色
              - 自动
              - 光线较亮时自动显示彩色，较暗时自动显示黑白。
              - 日夜切换阈值
              - 白天和黑夜自动模式下，黑白彩色切换的环境亮度阈值：
              - 恢复默认值
              - '0'
              - '100'

        device_name: 设备名称
        horizontal_flip: 水平翻转
        image_layout: 图像布局
        vertical_flip: 垂直翻转
        watermark: 水印
        date: 日期

        image_setting:
          name: '图像设置(只需要确认亮度同步/hdr/夜视通透模式/抗闪烁)'

          brightness: '亮度'
          contrast: '对比度'
          saturation: '饱和度'
          sharpness: '锐度'
          brightness_sync: false
          hdr: false
          night_transparent_vision: false
          anti_flicker: true

        options:
          - 垂直翻转
          - 水平翻转
          - 码流
          - 设备名称
          - 日期
          - 水印
          - 图像设置
          - 白天和黑夜
          - 遮盖区域
          - 图像布局

        private_mark:
          name: '遮盖区域'
          desc: '设置>显示>遮盖区域'
          type: 'navigation'
          camera_type: 'DM'
          mask_num: 4

        stream:
          clear:
            frame_rate:
              desc: 设置>显示>码流>码流>清晰>帧率(FPS)
              name: 帧率(FPS)
              options:
              - '25(默认)'
              - '22'
              - '20'
              - '18'
              - '16'
              - '15'
              - '12'
              - '10'
              - '8'
              - '6'
              - '4'
              - '2'

            i_frame_interval:
              desc: 设置>显示>码流>码流>清晰>I 帧间隔
              name: I 帧间隔
              options:
              - 1x
              - 2x

            max_bit_rate:
              desc: 设置>显示>码流>码流>清晰>最大码率(Kbps)
              name: 最大码率(Kbps)
              options:
              - '4096'
              - '5120'
              - '6144(默认)'
              - '7168'
              - '8192'

            resolution:
              desc: 设置>显示>码流>码流>清晰>分辨率
              name: 分辨率
              options:
                - '2560*2560'
                - '3200*3200'

            text:
              - I 帧间隔

          fluent:
            frame_rate:
              desc: 设置>显示>码流>码流>流畅>帧率(FPS)
              name: 帧率(FPS)
              options:
              - '15'
              - '10(默认)'
              - '7'
              - '4'

            i_frame_interval:
              desc: 设置>显示>码流>码流>流畅>I 帧间隔
              name: I 帧间隔
              options:
              - 1x
              - 2x
              - 3x
              - 4x

            max_bit_rate:
              desc: 设置>显示>码流>码流>流畅>最大码率(Kbps)
              options:
              - '64'
              - '128'
              - '160'
              - '192'
              - '256(默认)'
              - '384'
              - '512'

            resolution:
              desc: 设置>显示>码流>码流>流畅>分辨率
              name: 分辨率
              options:
                - 1024*1024

            text:
              - I 帧间隔

          frame_rate_mode:
            name: '帧率控制(A代表自动，B代表恒定，C代表逐步)'
            desc: '设置>显示>码流>码流>帧率控制'
            support_mode: 'ABC'

          text:
            - 'I 帧间隔'
          options:
            - '帧率控制'

        text:
        - 垂直翻转
        - 水平翻转
        - 码流
        - 设备名称
        - 日期
        - 水印
        - 图像设置
        - 白天和黑夜
        - 遮盖区域
        - 图像布局




