device_list_name: "Argus 2"
uid: '952700014C9A7UNU'

ipc:
  pir:
    items:
      pir:
        is_there_speaker: '设备是否有喇叭，有和无的情况页面文案不一样，有则保留无则删除'
        plan: '计划表，有则保留无则删除'
        sensitivity: '探测精度'

