device_list_name: "Keen Ranger PT"
uid: '952700Y001B610YD'

ipc:
  light:
    text:
      - ''

    items:
      light:
        text:
          - '红外灯'

        infrared_light:
          options:
            - ''


