device_list_name: Reolink Video Doorbell PoE-UOYB
uid: 952700Y10103UOYB

ipc:
  camera_record:
    items:
      alarm_recording_plan:
        alarm_type:
          options:
            - '响铃'
            - '画面变动'
            - '人'

      record_delay_duration:
        options:
          - '15秒'
          - '30秒'
          - '1分钟'

      pre_record: '预录像（有则保留无则删除）'

      timed_recording_plan:
        alarm_type:
          options:
            - ''


