device_list_name: "566-RLC-510A"
uid: '952700Y001XK19MG'

ipc:
  light:
    text:
      - ''

    items:
      light:
        text:
          - '红外灯'

        infrared_light:
          options:
            - ''

