device_list_name: "dbb 1AA1"
uid: '952700Y101JN1AA1'

ipc:
  light:
    text:
      - ''

    items:
      light:
        text:
          - '指示灯'
          - '红外灯'
          - '按钮灯'

        status_lights: '指示灯'

        infrared_light:
          options:
            - ''

        button_light:
          name: '按钮灯'
          light_off_mode:
            name: '关闭'
            desc: '设置>灯>按钮灯>关闭'
            type: 'menu'

          light_auto_mode:
            name: '自动'
            desc: '设置>灯>按钮灯>自动'
            type: 'menu'

          light_auto_on_night_mode:
            name: '自动且夜间常亮'
            desc: '设置>灯>按钮灯>自动且夜间常亮'
            type: 'menu'

          light_always_on_mode:
            name: '常亮'
            desc: '设置>灯>按钮灯>自动且夜间常亮'
            type: 'menu'
