device_list_name: "dbb 1AA1"
uid: '952700Y101JN1AA1'

ipc:
  pir:
    items:
      pir:
        sensitivity: '探测精度'

        trigger_interval:
          options:
            - '不限制'
            - '30s'
            - '1min'
            - '3min'
            - '5min'
            - '10min'
            - '30min'
            - '40min'
            - '50min'
            - '1h'
            - '2h'
            - '3h'
            - '4h'
            - '5h'
            - '6h'
            - '7h'
            - '8h'
            - '9h'
            - '10h'
            - '11h'
            - '12h'

