device_list_name: "Argus Eco Pro"
uid: '952700Y004681G6Q'

ipc:
  push:
    items:
      supported_test: '是否支持测试按钮，支持就保留该键，否则删除'

      device_notify_ringtone:
        alarm_ring: '报警铃声'

      schedule:
        alarm_type:
          options:
            - '响铃'
            - '画面变动'
            - '人'
            - '车'
            - '动物'
            - '其他'

