device_list_name: "Reolink Video Doorbell-137Z"
uid: '952700Y0061K137Z'

ipc:
  push:
    items:
      supported_test: '是否支持测试按钮，支持就保留该键，否则删除'

      visitor_phone_remind: '访客电话提醒'

      device_notify_ringtone:
        alarm_ring: '报警铃声'

      schedule:
        alarm_type:
          options:
            - '响铃'
            - '人'
            - '车'
            - '包裹'
            - '其他'

