device_list_name: "Reolink Duo 3 PoE"
uid: '952700Y1007SIHX8'

ipc:
  light:
    name: '灯'
    desc: '设置>灯'
    type: 'navigation'
    text:
      - ''

    items:
      light:
        text:
          - '红外灯'
          - '照明灯'

        infrared_light:
          options:
            - ''

        floodlight:
          light_off_mode:
            name: '关闭'
            desc: '设置>灯>照明灯>关闭'
            type: 'menu'
            text:
              - ''

          timer_mode:
            name: '定时模式'
            desc: '设置>灯>照明灯>定时模式'
            type: 'menu'
            text:
              - ''

          night_smart_mode:
            detect_type:
              option_text:
                - '人'
                - '车'
                - '动物'
