device_list_name: E1-17QT
uid: 95270004V3TR17QT

ipc:
  light:
    text:
      - ''

    items:
      light:
        text:
          - '状态灯'
          - '红外灯'

        status_lights: '状态灯(有则保留无则删除)'

        infrared_light:
          options:
            - ''

