device_list_name: "Reolink Video Doorbell WiFi-W"
uid: '952700Y0058Y1MGY'

ipc:
  push:
    items:
      supported_test: '是否支持测试按钮，支持就保留该键，否则删除'

      visitor_phone_remind: '访客电话提醒'

      device_notify_ringtone:
        alarm_ring: '报警铃声'

      schedule:
        alarm_type:
          options:
            - '响铃'
            - '画面变动'
            - '人'
            - '车'
            - '包裹'

      push_interval:
        options:
          - '20秒'
          - '30秒'
          - '60秒'
          - '120秒'
