device_list_name: D340W-White
uid: 95270008100J1JXO

ipc:
  light:
    text:
      - ''

    items:
      light:
        text:
          - '红外灯'
          - '按钮灯'

        infrared_light:
          options:
            - '亮度(此处只需要确认切换自动时亮度是否存在，否则留空)'

        button_light:
          light_off_mode: '关闭(有则保留无则删除)'
          light_auto_mode: '自动(有则保留无则删除)'
          light_auto_on_night_mode: '自动且夜间常亮(有则保留无则删除)'
          light_always_on_mode: '常亮(有则保留无则删除)'


