device_list_name: "RLC-842A-1TFW"
uid: '952700Y100UL1TFW'

ipc:
  light:
    text:
      - ''

    items:
      light:
        text:
          - '红外灯'

        infrared_light:
          options:
            - ''

