device_list_name: E1 Pro-FHOF
uid: 952700Y100VDFHOF

ipc:
  light:
    text:
      - ''

    items:
      light:
        text:
          - '状态灯'
          - '红外灯'

        status_lights: '状态灯(有则保留无则删除)'

        infrared_light:
          options:
            - ''

