device_list_name: "CX410-5KA1"
uid: '952700Y005K15KA1'

ipc:
  light:
    text:
      - ''

    items:
      light:
        text:
          - '照明灯'

        floodlight:
          light_off_mode: '关闭'

          timer_mode: '定时模式'

          auto_mode: '自动模式'

          smart_mode:
            detect_type:
              option_text:
                - '人'
                - '车'
                - '动物'
