device_list_name: "Reolink Argus 3 Pro-13x4"
uid: '952700Y003VK13X4'

ipc:
  Wi_Fi:
    text:
      - ''

    items:
      wifi:
        wifi_speed_test: 'Wi-Fi测速'
        add_other_network: '添加其他网络'
